import { User } from "./api/types"
import type { Product, Order, AdminStats } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Palm Oil",
    description: "Fresh red palm oil from Abia State. Rich in vitamins and perfect for authentic Nigerian cooking.",
    price: 25.99,
    unit: "per 1 litre",
    category: "Palm Products",
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
    stockQuantity: 50,
    origin: "Abia State, Nigeria",
    weight: "1kg",
    isFeatured: true,
  },
  {
    id: "2",
    name: "Dried Stockfish (Okporoko)",
    description: "Premium quality dried cod fish, essential for pepper soup and traditional stews.",
    price: 45.0,
    unit: "per 500g",
    category: "Dried Fish & Meat",
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
    stockQuantity: 30,
    origin: "Norway/Nigeria",
    weight: "500g",
    isFeatured: true,
  },
  {
    id: "3",
    name: "Egusi Seeds (Ground)",
    description: "Freshly ground melon seeds for the perfect Egusi soup. Sourced directly from Nigerian farms.",
    price: 18.5,
    unit: "per 250g",
    category: "Spices & Seasonings",
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
    stockQuantity: 75,
    origin: "Kano State, Nigeria",
    weight: "250g",
    isFeatured: true,
  },
  {
    id: "4",
    name: "Scotch Bonnet Pepper (Dried)",
    description: "Authentic Nigerian hot peppers, dried and ready for your spicy dishes.",
    price: 12.99,
    unit: "per 100g",
    category: "Spices & Seasonings",
    image: "/placeholder.svg?height=300&width=300",
    inStock: false,
    stockQuantity: 0,
    origin: "Lagos State, Nigeria",
    weight: "100g",
    isFeatured: true,
  },
  {
    id: "5",
    name: "Plantain Flour",
    description: "Unripe plantain flour, perfect for amala and other traditional dishes.",
    price: 22.0,
    unit: "per 1kg",
    category: "Grains & Cereals",
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
    stockQuantity: 40,
    origin: "Ogun State, Nigeria",
    weight: "1kg",
  },
  {
    id: "6",
    name: "Bitter Kola (Garcinia)",
    description: "Fresh bitter kola nuts, known for their medicinal properties and cultural significance.",
    price: 35.0,
    unit: "per 200g",
    category: "Snacks & Sweets",
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
    stockQuantity: 25,
    origin: "Cross River State, Nigeria",
    weight: "200g",
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    userId: "user-1",
    items: [
      { product: mockProducts[0], quantity: 2 },
      { product: mockProducts[2], quantity: 1 },
    ],
    total: 70.48,
    status: "delivered",
    createdAt: "2024-01-15T10:30:00Z",
    trackingNumber: "TRK123456789",
    shippingAddress: {
      fullName: "John Adebayo",
      email: "john@example.com",
      phone: "+1-555-0123",
      country: "United States",
      city: "Houston",
      streetAddress: "123 Main St, Apt 4B",
      postalCode: "77001",
      deliveryNotes: "Leave at front door",
    },
  },
  {
    id: "ORD-002",
    userId: "user-1",
    items: [
      { product: mockProducts[1], quantity: 1 },
      { product: mockProducts[4], quantity: 2 },
    ],
    total: 89.0,
    status: "shipped",
    createdAt: "2024-01-20T14:15:00Z",
    trackingNumber: "TRK987654321",
    shippingAddress: {
      fullName: "John Adebayo",
      email: "john@example.com",
      phone: "+1-555-0123",
      country: "United States",
      city: "Houston",
      streetAddress: "123 Main St, Apt 4B",
      postalCode: "77001",
    },
  },
]

export const mockUser: User = {
  id: "user-1",
  name: "John Adebayo",
  email: "john@example.com",
  phone: "+1-555-0123",
  preferredCountry: "United States",
  createdAt: "2023-12-01T00:00:00Z",
  role: "user",
  isActive: true,
  emailVerified:true,
  phoneVerified: true,
  addresses: [
    {
      fullName: "John Adebayo",
      email: "john@example.com",
      phone: "+1-555-0123",
      country: "United States",
      city: "Houston",
      streetAddress: "123 Main St, Apt 4B",
      postalCode: "77001",
      deliveryNotes: "Leave at front door",
    },
  ],
}

export const mockAdminStats: AdminStats = {
  totalRevenue: 15420.5,
  totalOrders: 156,
  bestSellingProduct: "Premium Palm Oil",
  activeCustomers: 89,
}
